### ISSUE TITLE
Option for reports to be sent to click-destination also

### ISSUE THREAD

**Issue by michael-oneill** [privacycg/private-click-measurement#48]
Since the advertiser (click-destination controller) will often be paying the publisher for conversions shouldn't they also receive the conversion reports? As usual no cookies, asynchronous delivery etc.  so no privacy impact, but it would help with getting agreement with what is owed, especially once the fraud detection is there.

This may have been mentioned before, for which apologies if so.

**Comment by johnwilander** [comment]
Hi!

This has been mentioned earlier and our intention is for the modern JavaScript reporting API to allow for reports to either endpoint or both.

**Comment by csharrison** [comment]
@johnwilander I wonder if this is an opportunity to align with our conversion measurement proposal which has a separate field for registering a reporting endpoint on the ad impression side. In our case we want to allow arbitrary reporting endpoints but for Safari's implementation it could be a restricted subset which just includes the source or destination site.

In our case there was a goal to have the two parties (publisher / advertiser) agree where the reports were sent which is why there are mechanisms on both impression / conversion registration for configuring this.

**Comment by johnwilander** [comment]
I should have called out your issue when I filed https://github.com/privacycg/private-click-measurement/issues/53, Michael. Sorry about that. Closing this one in favor of #53.
