### ISSUE TITLE
Step 6 is unclear

### ISSUE THREAD

**Issue by arthuredelstein** [privacycg/private-click-measurement#51]
What gets sent in Step 6's HTTP request coming from the destination website? Is it the `ad campaign id`? 

https://github.com/privacycg/private-click-measurement/blob/6b502254aca4527a6a754bb8ea301535b2974d69/private-click-measurement.bs#L77

And should it be a different URL from Step 7?

**Comment by johnwilander** [comment]
> What gets sent in Step 6's HTTP request coming from the destination website? Is it the `ad campaign id`?
> 
> https://github.com/privacycg/private-click-measurement/blob/6b502254aca4527a6a754bb8ea301535b2974d69/private-click-measurement.bs#L77

I believe the numbered list was deliberately made brief with details further down. This request is the result of a tracking pixel, typically a redirected one. Since neither the third-party nor the first-party can know if there is a pending ad click or for which ad campaigns there is a pending ad click, they cannot supply the ad campaign ID. Instead, this is where the conversion value is supplied. "A conversion happened with value NN. If you have a pending ad click that matches this third-party domain, please schedule a report with the ad campaign ID and the conversion value."

> And should it be a different URL from Step 7?

In the current spec, these requests differ in that the first one is an idempotent HTTP Get and the second one is a state changing HTTP POST. That's why they can use the same URL. However, there is an ongoing discussion on the format and specifics of the report request so they may get different paths in the end.

**Comment by johannhof** [comment]
This issue can probably be closed, or is there a need to make this clearer in the draft?

**Comment by johnwilander** [comment]
This should be clear in the spec now: https://github.com/privacycg/private-click-measurement/commit/f7e51bebbedc90419d6e39ea7cebb1d8ab687cc3
