### ISSUE TITLE
incentives for usage by advertisers and publishers

### ISSUE THREAD

**Issue by diminutivesloop** [privacycg/private-click-measurement#62]
Are there any incentives or technical restrictions that will push advertisers and publishers towards using this standard instead of just tracking ad clicks and conversions by embedding campaign IDs in ad link URLs and storing those IDs for later attribution as first-party cookies on the advertiser's site? I'm largely unfamiliar with the ad-tech space and I'm sure there are new browser privacy-protections in the works so I may be missing something here. There already was a [similar discussion](https://github.com/WICG/conversion-measurement-api/issues/35) on the Conversion Measurement API repo but it didn't clear anything up for me.

**Comment by johnwilander** [comment]
First of all, users and legislators are very interested in enhancing privacy online and they will likely be pushing in that direction both of them. Second, I personally reckon many advertisers will want to be privacy friendly to build good relationships with their current and future customers. It's important to get out of the headspace where it's just assumed that violating people's privacy is a normal and an OK thing to do. We're in the middle of a societal change in the privacy space. Third, many browsers now deploy tracking prevention and are improving protections all the time so link decoration tracking may not continue to work since it's a case of cross-site tracking. Fourth, many users feel they need to take drastic measures to protect their privacy online and those measures often block ads all together. For advertising to continue to be a steady source of revenue on the web, we should make sure people don't feel like blocking ads is the only way to get privacy. Finally, there may be policies on specific platforms or in specific browsers which prohibit tracking of individual users, devices, and events across websites, and on such platforms advertisers will want a privacy-preserving alternative to tracking.

A simple way of thinking about this is that we should make sure that they web is a safe place for users and also a great place to advertise. Therefore it's our duty to invent and standardize privacy-preserving ways to do web advertising.

**Comment by johnwilander** [comment]
I think this issue was more of a question and I did answer it above. Please file a new issue if you have further questions or concerns. Thanks!
